name: 'Lint PR Description'
description: 'Ensures the PR Description has been completed correctly'
author: 'craigbroadman'
inputs:
  message: 
    required: false
    description: 'A comment to add to the PR'
    default: 'Nice PR!'
runs:
  using: 'node12'
  main: 'dist/index.js'

