name: 'Lint PR Description'
description: 'Ensures the PR Description has been completed correctly'
author: 'craigbroadman'
inputs:
  repo-token:
    description: 'Token with permissions to do repo things'
    default: 'Nice PR!'
  message:
    required: false
    description: 'A comment to add to the PR'
    default: 'Nice PR!'
runs:
  using: 'node12'
  main: 'dist/index.js'