name: Release - Set Semantic Version.

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic
        with:
          extra_plugins: |
            conventional-changelog-conventionalcommits@latest
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
